In [61]:
import pandas as pd
from geopy.geocoders import Photon
from geopy.geocoders import Nominatim
from unidecode import unidecode
import numpy as np
from shapely.geometry import Point, Polygon
import geopandas as gpd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler


from geopy.distance import geodesic

In [19]:
import seaborn as sns
import geopandas as gpd
from shapely import wkt
import matplotlib.pyplot as plt
import pulp

In [38]:
!pip install pulp

Requirement already satisfied: pulp in c:\users\puria\anaconda3\lib\site-packages (2.9.0)

## UFLP,

In [93]:
inm = pd.read_csv('C:\\Users\\puria\\Documents\\articulo\\Mapa_Migracion_Irregular_Mexico\\project\\3.datos\\1. distribution_infraestructura\\1. Estaciones INM\\inm_gdp.csv')

In [94]:
inm_opt = gpd.read_file("C:\\Users\\puria\\Documents\\articulo\\Mapa_Migracion_Irregular_Mexico\\project\\1.Mapas\\UFLP\\57 opt\\facilities57.shp")

In [95]:
print(inm_opt.head(1))

   FID                    geometry
0    0  POINT (-93.66344 17.76210)

In [96]:
import geopandas as gpd
from shapely.geometry import Point

# Suponiendo que 'inm' es tu dataframe original
# Crear una columna 'geometry' usando latitud y longitud
geometry = [Point(xy) for xy in zip(inm['longitud'], inm['latitud'])]

# Crear el GeoDataFrame
gdf = gpd.GeoDataFrame(inm, geometry=geometry)

# Si solo quieres conservar la columna 'geometry' en un GeoDataFrame diferente:
inm = gdf[['geometry']]

# Mostrar el resultado
inm.head()

                      geometry
0   POINT (-94.92108 18.00185)
1  POINT (-109.56037 31.33295)
2  POINT (-102.32022 21.92955)
3   POINT (-90.53974 19.84566)
4   POINT (-92.07211 16.14993)

In [97]:
inm['etiquetas'] = 'original'
inm_opt['etiquetas'] = 'optimas'

# Para eliminar una columna en un GeoDataFrame o DataFrame
inm_opt = inm_opt.drop('FID', axis=1)

C:\Users\puria\anaconda3\Lib\site-packages\geopandas\geodataframe.py:1528: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [98]:
# Supongamos que tienes dos dataframes: df1 y df2
inm_opt_conc= pd.concat([inm, inm_opt], ignore_index=True)

In [99]:
inm_opt_conc

                        geometry etiquetas
0     POINT (-94.92108 18.00185)  original
1    POINT (-109.56037 31.33295)  original
2    POINT (-102.32022 21.92955)  original
3     POINT (-90.53974 19.84566)  original
4     POINT (-92.07211 16.14993)  original
..                           ...       ...
109   POINT (-97.92302 19.31343)   optimas
110  POINT (-100.93223 29.32488)   optimas
111   POINT (-91.34586 17.79752)   optimas
112   POINT (-96.72238 18.81423)   optimas
113  POINT (-112.71175 31.69498)   optimas

[114 rows x 2 columns]

In [100]:
# Iterar por todas las filas con etiquetas == 'original'
for idx_org, fila_org in inm_opt_conc[inm_opt_conc['etiquetas'] == 'original'].iterrows():
    # Lista para almacenar las filas 'optimas' dentro del rango de 30 km
    filas_cercanas = []

    # Iterar por todas las filas con etiquetas == 'optimas'
    for idx_opt, fila_opt in inm_opt_conc[inm_opt_conc['etiquetas'] == 'optimas'].iterrows():
        distancia = calcular_distancia(fila_org.geometry, fila_opt.geometry)
        
        # Verificar si la distancia es menor o igual a 30 km
        if distancia <= 60:
            filas_cercanas.append((idx_opt, distancia))
    
    # Si hay filas cercanas, cambiar la etiqueta de la fila original a 'org/elim'
    if len(filas_cercanas) > 0:
        inm_opt_conc.at[idx_org, 'etiquetas'] = 'org/elim'

        # Encontrar la fila mÃ¡s cercana dentro del rango
        fila_mas_cercana = min(filas_cercanas, key=lambda x: x[1])
        
        # Cambiar la etiqueta de la fila mÃ¡s cercana a 'org/opt'
        inm_opt_conc.at[fila_mas_cercana[0], 'etiquetas'] = 'org/opt'

In [101]:
# Mostrar el dataframe actualizado
inm_opt_conc.tail(60)

                        geometry etiquetas
54    POINT (-92.94293 17.98996)  org/elim
55   POINT (-102.57806 22.76581)  original
56   POINT (-101.55397 17.64425)  original
57    POINT (-93.66344 17.76210)   optimas
58    POINT (-92.77479 18.02716)   org/opt
59    POINT (-92.26093 14.90429)   org/opt
60    POINT (-91.42202 17.47071)   org/opt
61    POINT (-94.91458 17.94879)   org/opt
62    POINT (-92.59611 17.76092)   optimas
63    POINT (-92.24196 14.63217)   optimas
64   POINT (-117.01953 32.53174)   org/opt
65    POINT (-92.50400 15.12213)   org/opt
66    POINT (-93.37533 17.99088)   optimas
67   POINT (-100.51484 28.70417)   org/opt
68    POINT (-93.90084 16.23447)   org/opt
69    POINT (-92.19675 14.87686)   optimas
70    POINT (-92.42867 15.02172)   org/opt
71   POINT (-111.11849 30.54109)   optimas
72    POINT (-93.20802 15.68500)   org/opt
73    POINT (-93.11596 16.75380)   org/opt
74    POINT (-92.94805 17.55665)   optimas
75   POINT (-110.96922 29.09482)   org/opt
76    POINT (-94.95440 17.74768)   optimas
77    POINT (-92.82534 17.59522)   optimas
78   POINT (-106.48565 31.73726)   org/opt
79    POINT (-91.98092 17.50919)   org/opt
80    POINT (-92.81201 17.72172)   optimas
81    POINT (-91.63973 17.69363)   org/opt
82    POINT (-98.27882 26.09077)   optimas
83    POINT (-99.09293 19.35912)   org/opt
84   POINT (-115.47490 32.64052)   org/opt
85    POINT (-94.90950 17.38793)   optimas
86   POINT (-100.08935 24.84559)   optimas
87    POINT (-98.20695 19.03841)   org/opt
88    POINT (-99.22307 19.71734)   optimas
89   POINT (-100.18875 25.78165)   org/opt
90    POINT (-94.28233 17.99264)   optimas
91   POINT (-110.94505 31.32851)   optimas
92   POINT (-100.97552 22.15483)   org/opt
93    POINT (-93.01150 16.70752)   org/opt
94    POINT (-95.96436 18.28167)   optimas
95    POINT (-92.09254 15.07074)   optimas
96    POINT (-94.91188 16.41333)   org/opt
97    POINT (-98.37816 19.34670)   optimas
98    POINT (-90.73858 18.60693)   org/opt
99    POINT (-99.15181 19.98074)   org/opt
100  POINT (-100.53005 26.00251)   optimas
101   POINT (-98.04861 19.40361)   org/opt
102   POINT (-96.66667 19.33333)   org/opt
103   POINT (-99.18114 25.79330)   optimas
104   POINT (-92.03793 17.76826)   org/opt
105  POINT (-106.00000 28.50000)   org/opt
106   POINT (-86.92634 21.07668)   optimas
107   POINT (-99.11356 19.41928)   optimas
108   POINT (-92.61289 15.17097)   org/opt
109   POINT (-97.92302 19.31343)   optimas
110  POINT (-100.93223 29.32488)   optimas
111   POINT (-91.34586 17.79752)   org/opt
112   POINT (-96.72238 18.81423)   optimas
113  POINT (-112.71175 31.69498)   optimas

In [105]:
# Revisar el CRS (sistema de coordenadas) del GeoDataFrame
print(inm_opt_conc.crs)
# Transformar el CRS al sistema de coordenadas EPSG:4326
inm_opt_conc = inm_opt_conc.set_crs(epsg=4326)


# Asegurar que la columna 'etiquetas' sea de tipo string
#inm_opt_conc['etiquetas'] = inm_opt_conc['etiquetas'].astype(str)

EPSG:4326

In [104]:
#inm_opt_conc['etiquetas'] = inm_opt_conc['etiquetas'].astype(str)
#inm_opt_conc['etiquetas'] = inm_opt_conc['etiquetas'].str.lower()  # Or .str.upper() for uppercase

inm_opt_conc['etiquetas'] = inm_opt_conc['etiquetas'].str.replace('/', '', regex=False)

In [106]:
#inm_opt_conc.to_file("C:\\Users\\puria\\Documents\\articulo\\Mapa_Migracion_Irregular_Mexico\\project\\1.Mapas\\UFLP\\inm_opt_conc1.shp")

## Mapa de riesgos

In [2]:
risk2023 = gpd.read_file("C:\\Users\\puria\\Documents\\articulo\\Mapa_Migracion_Irregular_Mexico\\project\\1.Mapas\\areas\\municipiosrisk1.shp")

In [17]:
#risk2023.to_file("C:\\Users\\puria\\Documents\\articulo\\Mapa_Migracion_Irregular_Mexico\\project\\1.Mapas\\areas\\municipiosrisk1.shp")

In [3]:
risk2023.head()

,nommun,cvemun,nomedo,area,R1,R2,R3,R4,region,RiesTotal,geometry
0,"Aguascalientes, Aguascalientes",1001,Aguascalientes,1168.762384,0.360084,0.372695,0.117251,0.662296,Centro,0.267699,"POLYGON ((-11370403.590 2520317.662, -11368883..."
1,"Asientos, Aguascalientes",1002,Aguascalientes,547.762077,0.019696,0.011381,0.017855,0.745202,Centro,0.074333,"POLYGON ((-11368305.122 2546014.561, -11367916..."
2,"Calvillo, Aguascalientes",1003,Aguascalientes,931.300088,0.019349,0.013107,0.013835,0.708078,Centro,0.070579,"POLYGON ((-11444356.824 2510725.426, -11444212..."
3,"Cosio, Aguascalientes",1004,Aguascalientes,128.907513,0.012770,0.010345,0.012474,0.704691,Centro,0.067622,"POLYGON ((-11387740.145 2566722.259, -11387556..."
4,"El Llano, Aguascalientes",1010,Aguascalientes,500.861359,0.012770,0.012417,0.011113,0.710027,Centro,0.068244,"POLYGON ((-11365483.996 2514328.561, -11364488..."

In [15]:
# Crear el subdataframe con las 10 filas con mayor valor en RiesTotal
top_10_risk = risk2023.nlargest(10, 'RiesTotal').drop(columns=['area', 'geometry','cvemun', 'nomedo'])

In [16]:
top_10_risk

,nommun,R1,R2,R3,R4,region,RiesTotal
15,"Tijuana, Baja California",1.000000,0.457260,0.565862,0.585604,Pacifico,0.554581
1699,"Puebla, Puebla",0.630525,0.777990,0.092139,0.285744,Centro,0.398975
187,"Juarez, Chihuahua",0.730252,0.366047,0.201493,0.699859,Centro,0.382770
339,"Leon, Guanajuato",0.285981,0.017941,1.000000,0.625275,Centro,0.378087
225,"Iztapalapa, Ciudad de Mexico",0.757954,0.484478,0.104633,0.212230,Centro,0.354452
222,"Cuauhtemoc, Ciudad de Mexico",0.757608,0.514760,0.063440,0.212230,Centro,0.351638
983,"Monterrey, Nuevo Leon",0.420682,0.642326,0.145765,0.573247,Golfo,0.349964
12,"Mexicali, Baja California",0.680042,0.243348,0.146692,0.946155,Pacifico,0.346367
1982,"Centro, Tabasco",0.253431,0.914778,0.024040,0.469173,Sur,0.337160
2103,"Acayucan, Veracruz de Ignacio de la Llave",0.015887,1.000000,0.013464,0.490261,Golfo,0.298193