In [3]:
import pandas as pd
from geopy.geocoders import Photon
from geopy.geocoders import Nominatim
from unidecode import unidecode
import numpy as np

from shapely.geometry import Point, Polygon
import geopandas as gpd

import matplotlib.pyplot as plt

In [91]:
from sklearn.preprocessing import MinMaxScaler

In [98]:
#risk2023.to_file("C:\\Users\\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\1. Mapas\Metodo_1\\areas\\municipiosrisk.shp")

C:\Users\puria\AppData\Local\Temp\ipykernel_11540\439854719.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  risk2023.to_file("C:\\Users\\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\1. Mapas\Metodo_1\\areas\\municipiosrisk.shp")

In [85]:
risk2023 = gpd.read_file("C:\\Users\\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\1. Mapas\Metodo_1\\areas\\municipiosrisk.shp")

In [99]:
risk2023.head(1)

,municipio_,cvemunic,nomedo,nommun,area,corrupcion,crimenorg,violencia,vio_muj,geometry,risk2_trato_general,risk2_abusos_autoridades,risk2_estado_instalaciones,risk2_delservpub,vio_inst
0,"Aguascalientes, Aguascalientes",1001,Aguascalientes,Aguascalientes,1168.762384,474.0,1462.0,1011.0,36.008395,"POLYGON ((-102.14207 22.07321, -102.12842 22.0...",28.187135,13.268622,11.241027,44.32964,37.2695

In [87]:
# Seleccionar las columnas que deseas integrar y renombrarlas
columns_to_merge = ['cvemunic', 'risk2_trato_general_normalizado_ajustado', 'risk2_abusos_autoridades_normalizado_ajustado', 'risk2_estado_instalaciones_normalizado_ajustado']

# Crear un diccionario para renombrar las columnas
columns_renamed = {
    'risk2_trato_general_normalizado_ajustado': 'risk2_trato_general',
    'risk2_abusos_autoridades_normalizado_ajustado': 'risk2_abusos_autoridades',
    'risk2_estado_instalaciones_normalizado_ajustado': 'risk2_estado_instalaciones'
}

# Seleccionar y renombrar las columnas en valores_emif
valores_emif_selected = valores_emif[columns_to_merge].rename(columns=columns_renamed)

# Hacer el merge de las dataframes usando la columna 'cvemunic'
risk2023 = risk2023.merge(valores_emif_selected, on='cvemunic', how='left')

In [92]:
# Inicializar el escalador
scaler = MinMaxScaler(feature_range=(1, 100))

# Normalizar los valores de la columna 'corrupcion'
risk2023['risk2_delservpub'] = scaler.fit_transform(risk2023[['corrupcion']])

In [96]:
# Asegúrate de que las columnas están en el DataFrame
columns_to_sum = ['risk2_trato_general', 'risk2_abusos_autoridades', 'risk2_estado_instalaciones', 'risk2_delservpub']

# Verifica si todas las columnas existen en el DataFrame
for col in columns_to_sum:
    if col not in risk2023.columns:
        print(f"Warning: Column '{col}' not found in the DataFrame.")
        
# Sumar las columnas
risk2023['total_vio_inst'] = risk2023[columns_to_sum].sum(axis=1)

# Inicializar el escalador
scaler = MinMaxScaler(feature_range=(1, 100))

# Normalizar los valores de la columna 'total_vio_inst'
risk2023['vio_inst'] = scaler.fit_transform(risk2023[['total_vio_inst']])

# Eliminar la columna 'total_vio_inst' si ya no es necesaria
risk2023.drop(columns=['total_vio_inst'], inplace=True)

### Normalizar todos los stats

## Stat 1: Violencia e Inseguridad Mujeres, Familias y Ninos.

From databse del secretariado ejectuvido del sistema nacional de seguridad publica.
es el numero de eventos en 2023, por division municipal de: 'Feminicidio','Tráfico de menores','La libertad y la seguridad sexual'; Acoso Sexucal, Abuso Sexual, Hostigamiento Sexual, Violacion Simple, Violacion Equiparada. Y 'La sociedad'; ,;, .

In [7]:
# Normalizar la columna 'Violencia' en una escala de 1 a 100
min_val = risk2023['Violencia'].min()
max_val = risk2023['Violencia'].max()

risk2023['Violencia_normalizada'] = (risk2023['Violencia'] - min_val) / (max_val - min_val) * 99 + 1

## Stat 2:

-'Delitos cometidos por servidores públicos' fromo databe secretariado ejectuvido del sistema nacional de seguridad publica. return 'Corrupción Institucional'

-emifsur - DEVUELTOS POR AUTORIDADES 
MEXICANA (contabilizacion abusos de autoridad)
S

In [31]:
emifdevgua1 = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\Guate-Julio-Septiembre 2022.csv")
emifdevgua2 = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\Guate-Octubre-Noviembre 2022.csv")
emifdevhon1 = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\hon-Julio-Septiembre 2022.csv")
emifdevhon2 = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\hon-Octubre-Noviembre 2022.csv")
emifdevsal1 = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\sal-Julio-Septiembre 2022.csv")
emifdevsal2 = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\sal-Octubre-Noviembre 2022.csv")

In [35]:
# Función para obtener columnas que comienzan con 'p34'
def obtener_columnas_p34(df):
    return [col for col in df.columns if col.startswith('p34')]

# Obtener columnas que comienzan con 'p34' para cada dataframe
columnas_p34_gua1 = obtener_columnas_p34(emifdevgua1)
columnas_p34_gua2 = obtener_columnas_p34(emifdevgua2)
columnas_p34_hon1 = obtener_columnas_p34(emifdevhon1)
columnas_p34_hon2 = obtener_columnas_p34(emifdevhon2)
columnas_p34_sal1 = obtener_columnas_p34(emifdevsal1)
columnas_p34_sal2 = obtener_columnas_p34(emifdevsal2)

# Contar las columnas que comienzan con 'p34' para cada dataframe
conteo_columnas_p34 = {
    'emifdevgua1': len(columnas_p34_gua1),
    'emifdevgua2': len(columnas_p34_gua2),
    'emifdevhon1': len(columnas_p34_hon1),
    'emifdevhon2': len(columnas_p34_hon2),
    'emifdevsal1': len(columnas_p34_sal1),
    'emifdevsal2': len(columnas_p34_sal2)
}

# Mostrar resultados
print("Columnas que comienzan con 'p34' y su conteo en cada dataframe:")
for df_name, count in conteo_columnas_p34.items():
    print(f"{df_name}: {count} columnas")
    if df_name == 'emifdevgua1':
        print(f"Columnas: {columnas_p34_gua1}")
    elif df_name == 'emifdevgua2':
        print(f"Columnas: {columnas_p34_gua2}")
    elif df_name == 'emifdevhon1':
        print(f"Columnas: {columnas_p34_hon1}")
    elif df_name == 'emifdevhon2':
        print(f"Columnas: {columnas_p34_hon2}")
    elif df_name == 'emifdevsal1':
        print(f"Columnas: {columnas_p34_sal1}")
    elif df_name == 'emifdevsal2':
        print(f"Columnas: {columnas_p34_sal2}")
    print()

# Comparar las listas de columnas para ver diferencias
columnas_set_gua1 = set(columnas_p34_gua1)
columnas_set_gua2 = set(columnas_p34_gua2)
columnas_set_hon1 = set(columnas_p34_hon1)
columnas_set_hon2 = set(columnas_p34_hon2)
columnas_set_sal1 = set(columnas_p34_sal1)
columnas_set_sal2 = set(columnas_p34_sal2)

diferencias_gua = columnas_set_gua1.symmetric_difference(columnas_set_gua2)
diferencias_hon = columnas_set_hon1.symmetric_difference(columnas_set_hon2)
diferencias_sal = columnas_set_sal1.symmetric_difference(columnas_set_sal2)

print(f"Diferencias entre Guate-Julio-Septiembre 2022 y Guate-Octubre-Noviembre 2022: {diferencias_gua}")
print(f"Diferencias entre hon-Julio-Septiembre 2022 y hon-Octubre-Noviembre 2022: {diferencias_hon}")
print(f"Diferencias entre sal-Julio-Septiembre 2022 y sal-Octubre-Noviembre 2022: {diferencias_sal}")

Columnas que comienzan con 'p34' y su conteo en cada dataframe:
emifdevgua1: 51 columnas
Columnas: ['p34e', 'p34m', 'p34l', 'p34u', 'p34_1', 'p34_1_1', 'p34_2', 'p34_2_1_1', 'p34_2_1_2', 'p34_2_1_3', 'p34_2_1_4', 'p34_2_1_5', 'p34_2_1_6', 'p34_2_2', 'p34_2_3_1', 'p34_2_3_2', 'p34_2_3_3', 'p34_3_0_1', 'p34_3_0_2', 'p34_3_0_3', 'p34_3_0_4', 'p34_3_1_1', 'p34_3_1_2', 'p34_3_1_3', 'p34_3_1_4', 'p34_4c', 'p34_4t', 'p34_5_1', 'p34_5_2', 'p34_5_3', 'p34_5_4', 'p34_5_5', 'p34_5_6', 'p34_5_7', 'p34_6', 'p34_7', 'p34_8', 'p34_9', 'p34_10_1', 'p34_10_2', 'p34_10_3', 'p34_10_4', 'p34_10_5', 'p34_10_6', 'p34_10_7', 'p34_10_8', 'p34_11', 'p34_12', 'p34_12_1', 'p34_13', 'p34_14']

emifdevgua2: 51 columnas
Columnas: ['p34e', 'p34m', 'p34l', 'p34u', 'p34_1', 'p34_1_1', 'p34_2', 'p34_2_1_1', 'p34_2_1_2', 'p34_2_1_3', 'p34_2_1_4', 'p34_2_1_5', 'p34_2_1_6', 'p34_2_2', 'p34_2_3_1', 'p34_2_3_2', 'p34_2_3_3', 'p34_3_0_1', 'p34_3_0_2', 'p34_3_0_3', 'p34_3_0_4', 'p34_3_1_1', 'p34_3_1_2', 'p34_3_1_3', 'p34_3_1_4', 'p34_4c', 'p34_4t', 'p34_5_1', 'p34_5_2', 'p34_5_3', 'p34_5_4', 'p34_5_5', 'p34_5_6', 'p34_5_7', 'p34_6', 'p34_7', 'p34_8', 'p34_9', 'p34_10_1', 'p34_10_2', 'p34_10_3', 'p34_10_4', 'p34_10_5', 'p34_10_6', 'p34_10_7', 'p34_10_8', 'p34_11', 'p34_12', 'p34_12_1', 'p34_13', 'p34_14']

emifdevhon1: 51 columnas
Columnas: ['p34e', 'p34m', 'p34l', 'p34u', 'p34_1', 'p34_1_1', 'p34_2', 'p34_2_1_1', 'p34_2_1_2', 'p34_2_1_3', 'p34_2_1_4', 'p34_2_1_5', 'p34_2_1_6', 'p34_2_2', 'p34_2_3_1', 'p34_2_3_2', 'p34_2_3_3', 'p34_3_0_1', 'p34_3_0_2', 'p34_3_0_3', 'p34_3_0_4', 'p34_3_1_1', 'p34_3_1_2', 'p34_3_1_3', 'p34_3_1_4', 'p34_4c', 'p34_4t', 'p34_5_1', 'p34_5_2', 'p34_5_3', 'p34_5_4', 'p34_5_5', 'p34_5_6', 'p34_5_7', 'p34_6', 'p34_7', 'p34_8', 'p34_9', 'p34_10_1', 'p34_10_2', 'p34_10_3', 'p34_10_4', 'p34_10_5', 'p34_10_6', 'p34_10_7', 'p34_10_8', 'p34_11', 'p34_12', 'p34_12_1', 'p34_13', 'p34_14']

emifdevhon2: 51 columnas
Columnas: ['p34e', 'p34m', 'p34l', 'p34u', 'p34_1', 'p34_1_1', 'p34_2', 'p34_2_1_1', 'p34_2_1_2', 'p34_2_1_3', 'p34_2_1_4', 'p34_2_1_5', 'p34_2_1_6', 'p34_2_2', 'p34_2_3_1', 'p34_2_3_2', 'p34_2_3_3', 'p34_3_0_1', 'p34_3_0_2', 'p34_3_0_3', 'p34_3_0_4', 'p34_3_1_1', 'p34_3_1_2', 'p34_3_1_3', 'p34_3_1_4', 'p34_4c', 'p34_4t', 'p34_5_1', 'p34_5_2', 'p34_5_3', 'p34_5_4', 'p34_5_5', 'p34_5_6', 'p34_5_7', 'p34_6', 'p34_7', 'p34_8', 'p34_9', 'p34_10_1', 'p34_10_2', 'p34_10_3', 'p34_10_4', 'p34_10_5', 'p34_10_6', 'p34_10_7', 'p34_10_8', 'p34_11', 'p34_12', 'p34_12_1', 'p34_13', 'p34_14']

emifdevsal1: 51 columnas
Columnas: ['p34e', 'p34m', 'p34l', 'p34u', 'p34_1', 'p34_1_1', 'p34_2', 'p34_2_1_1', 'p34_2_1_2', 'p34_2_1_3', 'p34_2_1_4', 'p34_2_1_5', 'p34_2_1_6', 'p34_2_2', 'p34_2_3_1', 'p34_2_3_2', 'p34_2_3_3', 'p34_3_0_1', 'p34_3_0_2', 'p34_3_0_3', 'p34_3_0_4', 'p34_3_1_1', 'p34_3_1_2', 'p34_3_1_3', 'p34_3_1_4', 'p34_4c', 'p34_4t', 'p34_5_1', 'p34_5_2', 'p34_5_3', 'p34_5_4', 'p34_5_5', 'p34_5_6', 'p34_5_7', 'p34_6', 'p34_7', 'p34_8', 'p34_9', 'p34_10_1', 'p34_10_2', 'p34_10_3', 'p34_10_4', 'p34_10_5', 'p34_10_6', 'p34_10_7', 'p34_10_8', 'p34_11', 'p34_12', 'p34_12_1', 'p34_13', 'p34_14']

emifdevsal2: 51 columnas
Columnas: ['p34e', 'p34m', 'p34l', 'p34u', 'p34_1', 'p34_1_1', 'p34_2', 'p34_2_1_1', 'p34_2_1_2', 'p34_2_1_3', 'p34_2_1_4', 'p34_2_1_5', 'p34_2_1_6', 'p34_2_2', 'p34_2_3_1', 'p34_2_3_2', 'p34_2_3_3', 'p34_3_0_1', 'p34_3_0_2', 'p34_3_0_3', 'p34_3_0_4', 'p34_3_1_1', 'p34_3_1_2', 'p34_3_1_3', 'p34_3_1_4', 'p34_4c', 'p34_4t', 'p34_5_1', 'p34_5_2', 'p34_5_3', 'p34_5_4', 'p34_5_5', 'p34_5_6', 'p34_5_7', 'p34_6', 'p34_7', 'p34_8', 'p34_9', 'p34_10_1', 'p34_10_2', 'p34_10_3', 'p34_10_4', 'p34_10_5', 'p34_10_6', 'p34_10_7', 'p34_10_8', 'p34_11', 'p34_12', 'p34_12_1', 'p34_13', 'p34_14']

Diferencias entre Guate-Julio-Septiembre 2022 y Guate-Octubre-Noviembre 2022: set()
Diferencias entre hon-Julio-Septiembre 2022 y hon-Octubre-Noviembre 2022: set()
Diferencias entre sal-Julio-Septiembre 2022 y sal-Octubre-Noviembre 2022: set()

In [33]:
emifdevhon1

,folio,unidad,trim,ciudad,punto,turno,p1,p2,p3a,p3n,...,p52,p52_1,p52_2,p52_3,nivel,oficio_mx,filtro,estrato,upm,ponfin3
0,709,12209,3,1,1,1,2,36,6,1,...,1,1,-44,-44,2,0,1,1011,1011012209,296.639812
1,1708,12208,3,1,1,1,2,25,3,3,...,1,2,2,1,4,0,1,1011,1011012208,127.281621
2,2208,12208,3,1,1,1,1,27,2,1,...,1,2,1,1,1,0,1,1011,1011012208,195.555395
3,3808,22208,3,1,1,1,1,24,3,2,...,-40,-40,-40,-40,3,0,1,1011,1011022208,316.767417
4,5708,32208,3,1,1,1,1,27,5,1,...,1,2,1,2,1,0,1,1011,1011032208,122.828182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,61308,242208,3,1,1,1,1,22,6,1,...,1,2,1,1,2,0,1,1011,1011242208,256.969486
70,66308,292208,3,1,1,1,1,37,3,1,...,1,1,-44,-44,1,7,1,1011,1011292208,127.676663
71,66608,292208,3,1,1,1,1,19,3,2,...,1,1,-44,-44,3,0,1,1011,1011292208,127.676663
72,66908,292208,3,1,1,1,1,19,0,0,...,-39,-39,-39,-39,0,0,1,1011,1011292208,127.676663
73,67008,292208,3,1,1,1,1,25,1,1,...,1,2,1,2,1,0,1,1011,1011292208,127.676663

In [45]:
# Concatenar los dataframes
emifdev_combined = pd.concat([emifdevgua1, emifdevgua2, emifdevhon1, emifdevhon2, emifdevsal1, emifdevsal2])

# Filtrar las columnas que comienzan con 'p34'
columnas_p34 = [col for col in emifdev_combined.columns if col.startswith('p34')]
 = emifdev_combined[columnas_p34]

# Verificar el número de filas y columnas en el dataframe filtrado
print(f"Número de filas en el dataframe combinado: {emifdev_combined.shape[0]}")
print(f"Número de columnas en el dataframe combinado: {emifdev_combined.shape[1]}")
print(f"Número de filas en el dataframe filtrado: {emifdev_filtrado.shape[0]}")
print(f"Número de columnas en el dataframe filtrado: {emifdev_filtrado.shape[1]}")

Número de filas en el dataframe combinado: 2218
Número de columnas en el dataframe combinado: 241
Número de filas en el dataframe filtrado: 2218
Número de columnas en el dataframe filtrado: 51

In [59]:
#emifdev_filtrado.to_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\vio_inst_emifsurdev.csv")

In [60]:
emifdev_filtrado = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\vio_inst_emifsurdev.csv")

In [43]:
dicc = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\DMXGT_Valores_2022.csv")

In [44]:
dicc

        Variable  Valor                   Etiqueta
0           trim      3             Jul - Sep 2022
1          punto     97                    No sabe
2          punto     98                No responde
3          punto     99            No especificado
4          turno      1                      Único
...          ...    ...                        ...
19716  oficio_mx      6                 Domésticos
19717  oficio_mx      7                  Servicios
19718  oficio_mx      8             Profesionistas
19719  oficio_mx     99            No especificado
19720     filtro      1  Desplazamiento migratorio

[19721 rows x 3 columns]

In [55]:
# Crear diccionarios de mapeo para cada columna de interés
mapeo_p34e = dicc[dicc['Variable'] == 'p34e'].set_index('Valor')['Etiqueta'].to_dict()
mapeo_p34m = dicc[dicc['Variable'] == 'p34m'].set_index('Valor')['Etiqueta'].to_dict()
mapeo_p34l = dicc[dicc['Variable'] == 'p34l'].set_index('Valor')['Etiqueta'].to_dict()

# Crear una nueva columna 'cvemunic' con los valores originales de 'p34m'
emifdev_filtrado['cvemunic'] = emifdev_filtrado['p34m']

# Aplicar los diccionarios de mapeo a las columnas correspondientes en emifdev_filtrado
emifdev_filtrado['p34e'] = emifdev_filtrado['p34e'].map(mapeo_p34e)
emifdev_filtrado['p34m'] = emifdev_filtrado['p34m'].map(mapeo_p34m)
emifdev_filtrado['p34l'] = emifdev_filtrado['p34l'].map(mapeo_p34l)

In [57]:
# Realizar el join para agregar la columna 'municipio_' a emifdev_filtrado basado en 'cvemunic'
emifdev_filtrado = emifdev_filtrado.merge(risk2023[['cvemunic', 'municipio_']], on='cvemunic', how='left')

In [63]:
emifdev_filtrado.head()

,municipio_,cvemunic,p34e,p34m,p34l,p34u,p34_1,p34_1_1,p34_2,p34_2_1_1,...,p34_10_5,p34_10_6,p34_10_7,p34_10_8,p34_11,p34_12,p34_12_1,p34_13,p34_14,Unnamed: 53
0,"Benito Juarez, Ciudad de Mexico",9014,Distrito Federal,Benito Juárez,Benito Juárez (Distrito Federal),2,3,2,2,1,...,1,1,1,2,1,2,-32,2,-33,NaN
1,"Cuernavaca, Morelos",17007,Morelos,Cuernavaca,Cuernavaca (Morelos),2,3,2,2,1,...,1,1,1,2,1,2,-32,2,-33,NaN
2,"Cuauhtemoc, Ciudad de Mexico",9015,Distrito Federal,Cuauhtémoc,Cuauhtémoc (Distrito Federal),2,4,1,3,2,...,2,2,2,2,1,2,-32,2,-33,NaN
3,"Benito Juarez, Ciudad de Mexico",9014,Distrito Federal,Benito Juárez,Benito Juárez (Distrito Federal),2,4,1,2,2,...,2,2,2,2,1,2,-32,2,-33,NaN
4,"Puebla, Puebla",21114,Puebla,Puebla,Heróica Puebla de Zaragoza (Puebla),2,8,1,3,1,...,2,2,2,2,1,2,-32,2,-33,NaN

### scores stat 2

In [64]:
# Crear un dataframe con el conteo de apariciones de cada 'cvemunic'
valores_emif = emifdev_filtrado.groupby(['cvemunic', 'municipio_']).size().reset_index(name='frec_app')

# Crear las columnas 'p34_2:4frec' y 'p34_2:5frec'
valores_emif['p34_2:4frec'] = emifdev_filtrado[emifdev_filtrado['p34_2'] == 4].groupby('cvemunic').size().reindex(valores_emif['cvemunic'], fill_value=0).values
valores_emif['p34_2:5frec'] = emifdev_filtrado[emifdev_filtrado['p34_2'] == 5].groupby('cvemunic').size().reindex(valores_emif['cvemunic'], fill_value=0).values

# Calcular 'p34_2_score'
valores_emif['p34_2_score'] = valores_emif['p34_2:4frec'] * 30 + valores_emif['p34_2:5frec'] * 70

# Crear las columnas 'p34_3_0_1frec', 'p34_3_0_2frec', 'p34_3_0_3frec', 'p34_3_0_4frec'
for col in ['p34_3_0_1', 'p34_3_0_2', 'p34_3_0_3', 'p34_3_0_4']:
    valores_emif[col + 'frec'] = emifdev_filtrado[emifdev_filtrado[col] == 1].groupby('cvemunic').size().reindex(valores_emif['cvemunic'], fill_value=0).values

# Calcular 'p34_3_score'
valores_emif['p34_3_score'] = valores_emif[['p34_3_0_1frec', 'p34_3_0_2frec', 'p34_3_0_3frec', 'p34_3_0_4frec']].sum(axis=1) * 25

# Crear las columnas 'p34_5_1frec', 'p34_5_2frec', 'p34_5_3frec', 'p34_5_4frec', 'p34_5_5frec', 'p34_5_6frec', 'p34_5_7frec'
for col in ['p34_5_1', 'p34_5_2', 'p34_5_3', 'p34_5_4', 'p34_5_5', 'p34_5_6', 'p34_5_7']:
    valores_emif[col + 'frec'] = emifdev_filtrado[emifdev_filtrado[col] == 2].groupby('cvemunic').size().reindex(valores_emif['cvemunic'], fill_value=0).values

# Calcular 'p34_5_score'
valores_emif['p34_5_score'] = valores_emif[['p34_5_1frec', 'p34_5_2frec', 'p34_5_3frec', 'p34_5_4frec', 'p34_5_5frec', 'p34_5_6frec', 'p34_5_7frec']].sum(axis=1) * 14.28

In [94]:
#valores_emif.to_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\vio_inst_emifsurdev_scores.csv")

In [80]:
valores_emif = pd.read_csv("C:\\Users\puria\\Mapa_Migracion_Irregular_Mexico\\1. Mapas\\3.datos\\2. datos_estadisticos\\3. risks\\EMIF-Devueltos\\vio_inst_emifsurdev_scores.csv")

In [72]:
# Ordenar el DataFrame de mayor a menor basado en la columna 'frec_app'
valores_emif_sorted = valores_emif.sort_values(by='p34_2:4frec', ascending=False)

In [95]:
valores_emif.head(10)

,Unnamed: 0,cvemunic,municipio_,frec_app,p34_2:4frec,p34_2:5frec,p34_2_score,p34_3_0_1frec,p34_3_0_2frec,p34_3_0_3frec,...,risk2_estado_instalaciones,risk2_trato_general_normalizado,risk2_abusos_autoridades_normalizado,risk2_estado_instalaciones_normalizado,risk2_trato_general_ajustado,risk2_abusos_autoridades_ajustado,risk2_estado_instalaciones_ajustado,risk2_trato_general_normalizado_ajustado,risk2_abusos_autoridades_normalizado_ajustado,risk2_estado_instalaciones_normalizado_ajustado
0,0,1001,"Aguascalientes, Aguascalientes",10,0,1,70,1,1,2,...,51.408,10.000000,20.000000,51.428571,29.192267,41.703239,214.388012,28.187135,13.268622,11.241027
1,1,2001,"Ensenada, Baja California",3,0,1,70,1,1,1,...,71.400,33.333333,50.000000,71.428571,50.494326,54.101064,154.512639,48.755733,17.213209,8.101576
2,2,2002,"Mexicali, Baja California",10,0,0,0,3,2,0,...,82.824,0.000000,30.000000,82.857143,0.000000,62.554859,345.402908,0.000000,19.902933,18.110543
3,3,2004,"Tijuana, Baja California",15,4,0,120,6,1,1,...,59.024,11.428571,26.666667,59.047619,43.280851,72.134752,319.326120,41.790628,22.950946,16.743257
4,4,4001,"Calkini, Campeche",1,0,0,0,0,0,0,...,57.120,0.000000,0.000000,57.142857,0.000000,0.000000,82.406741,0.000000,0.000000,4.320840
5,5,4002,"Campeche, Campeche",3,0,0,0,1,1,0,...,33.320,0.000000,33.333333,33.333333,0.000000,36.067376,72.105898,0.000000,11.475473,3.780735
6,6,4004,"Champoton, Campeche",1,0,0,0,0,0,0,...,57.120,0.000000,0.000000,57.142857,0.000000,0.000000,82.406741,0.000000,0.000000,4.320840
7,7,4009,"Escarcega, Campeche",3,0,0,0,0,0,0,...,61.880,0.000000,0.000000,61.904762,0.000000,0.000000,133.910954,0.000000,0.000000,7.021366
8,8,5002,"Acuna, Coahuila de Zaragoza",2,0,0,0,0,0,0,...,49.980,0.000000,0.000000,50.000000,0.000000,0.000000,90.987513,0.000000,0.000000,4.770757
9,9,5003,"Allende, Coahuila de Zaragoza",1,0,0,0,0,0,0,...,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [82]:
import pandas as pd

# Supongamos que el dataframe valores_emif ya está cargado y contiene las columnas necesarias

# Calcular el score promedio para cada indicador
valores_emif['risk2_trato_general'] = valores_emif['p34_2_score'] / valores_emif['frec_app']
valores_emif['risk2_abusos_autoridades'] = valores_emif['p34_3_score'] / valores_emif['frec_app']
valores_emif['risk2_estado_instalaciones'] = valores_emif['p34_5_score'] / valores_emif['frec_app']

# Normalizar cada score en una escala de 0 a 100 utilizando el método min-max
def min_max_scaling(series):
    return (series - series.min()) / (series.max() - series.min()) * 100

valores_emif['risk2_trato_general_normalizado'] = min_max_scaling(valores_emif['risk2_trato_general'])
valores_emif['risk2_abusos_autoridades_normalizado'] = min_max_scaling(valores_emif['risk2_abusos_autoridades'])
valores_emif['risk2_estado_instalaciones_normalizado'] = min_max_scaling(valores_emif['risk2_estado_instalaciones'])

In [83]:
# Calcular el score promedio ajustado utilizando el logaritmo de frec_app
valores_emif['risk2_trato_general_ajustado'] = valores_emif['p34_2_score'] / np.log1p(valores_emif['frec_app'])
valores_emif['risk2_abusos_autoridades_ajustado'] = valores_emif['p34_3_score'] / np.log1p(valores_emif['frec_app'])
valores_emif['risk2_estado_instalaciones_ajustado'] = valores_emif['p34_5_score'] / np.log1p(valores_emif['frec_app'])

# Normalizar cada score ajustado en una escala de 0 a 100 utilizando el método min-max
valores_emif['risk2_trato_general_normalizado_ajustado'] = min_max_scaling(valores_emif['risk2_trato_general_ajustado'])
valores_emif['risk2_abusos_autoridades_normalizado_ajustado'] = min_max_scaling(valores_emif['risk2_abusos_autoridades_ajustado'])
valores_emif['risk2_estado_instalaciones_normalizado_ajustado'] = min_max_scaling(valores_emif['risk2_estado_instalaciones_ajustado'])

In [27]:
# Filtrar las columnas que comienzan con 'p34_3'
columnas_p34_3 = [col for col in emifdev1_filtrado.columns if col.startswith('p34_3')]

# Crear una máscara booleana para filtrar las filas que tienen el valor '1' en cualquiera de las columnas p34_3
mask = emifdev1_filtrado[columnas_p34_3].eq(1).any(axis=1)

# Filtrar el dataframe utilizando la máscara
emifdev1_filtrado_1 = emifdev1_filtrado[mask]

# Verificar el número de filas en el dataframe original y el filtrado
print(f"Número de filas en el dataframe original: {emifdev1_filtrado.shape[0]}")
print(f"Número de filas en el dataframe filtrado: {emifdev1_filtrado_1.shape[0]}")

Número de filas en el dataframe original: 796
Número de filas en el dataframe filtrado: 147

In [28]:
emifdev1_filtrado_1

,p34e,p34m,p34l,p34u,p34_1,p34_1_1,p34_2,p34_2_1_1,p34_2_1_2,p34_2_1_3,...,p34_10_4,p34_10_5,p34_10_6,p34_10_7,p34_10_8,p34_11,p34_12,p34_12_1,p34_13,p34_14
2,9,9015,90150001,2,4,1,3,2,2,2,...,2,2,2,2,2,1,2,-32,2,-33
4,21,21114,211140001,2,8,1,3,1,1,1,...,2,2,2,2,2,1,2,-32,2,-33
5,21,21114,211140001,2,8,2,3,1,1,1,...,1,1,1,1,1,1,2,-32,2,-33
6,21,21114,211140001,2,4,1,2,1,1,1,...,1,1,1,1,1,1,2,-32,2,-33
7,21,21114,211140001,2,4,1,2,1,1,1,...,1,1,1,1,1,1,2,-32,2,-33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
778,28,28032,280320001,2,4,1,3,1,2,2,...,2,2,2,1,2,2,2,-32,2,-33
783,28,28032,280320001,2,3,1,3,1,2,1,...,2,2,2,1,2,2,2,-32,2,-33
784,26,26002,260020001,2,3,1,3,1,2,2,...,2,2,2,1,2,2,2,-32,2,-33
790,28,99997,999999997,97,3,1,3,1,2,2,...,2,2,2,1,2,2,2,-32,2,-33
792,5,5022,50220560,1,7,1,5,1,2,2,...,2,2,2,1,2,1,2,-32,2,-33

In [13]:
emifdev1.columns

Index(['folio', 'trim', 'unidad', 'ciudad', 'punto', 'turno', 'p1', 'p2',
       'p3a', 'p3n',
       ...
       'p52', 'p52_1', 'p52_2', 'p52_3', 'nivel', 'oficio_mx', 'filtro',
       'estrato', 'upm', 'ponfin3'],
      dtype='object', length=237)

In [18]:
# Filtrar las columnas que comienzan con 'p34'
columnas_p34 = [col for col in emifdev1.columns if col.startswith('p34_3')]

# Crear un nuevo dataframe solo con las columnas filtradas
emifdev1_filtrado = emifdev1[columnas_p34]

In [19]:
emifdev1_filtrado.head()

,p34_3_0_1,p34_3_0_2,p34_3_0_3,p34_3_0_4,p34_3_1_1,p34_3_1_2,p34_3_1_3,p34_3_1_4
0,2,2,2,2,-31,-31,-31,-31
1,2,2,2,2,-31,-31,-31,-31
2,2,2,1,2,2,2,1,2
3,2,2,2,2,-31,-31,-31,-31
4,1,1,1,2,2,2,1,2

### Stat 3: Organized Crime Precense Perception

In [52]:
#mx_mun = gpd.read_file('/Users/pablouriarte/Mapa_Migracion_Irregular_Mexico_Fresh/1. Mapas/2. arcgis(general)/maps_boundaries/Municipalities/mapa_mexico_mun/Division_Municipal_Mexico_2010.shp').set_index('CLAVE').to_crs(epsg=4485)

In [68]:
# Crear la columna 'Cve. Municipio' concatenando 'CVE_EDO' y 'CVE_MUNI'
mx_mun['Cve. Municipio'] = mx_mun['CVE_EDO'].astype(str).str.zfill(2) + mx_mun['CVE_MUNI'].astype(str).str.zfill(3)

# Convertir la nueva columna a tipo entero para eliminar cualquier cero inicial no deseado
mx_mun['Cve. Municipio'] = mx_mun['Cve. Municipio'].astype(int)

In [92]:
mx_mun.info

<bound method DataFrame.info of                      NOM_MUN          NOMEDO CVE_EDO CVE_MUNI         Area  \
CLAVE
01001         Aguascalientes  Aguascalientes      01      001  1168.762384
01002               Asientos  Aguascalientes      01      002   547.762077
01003               Calvillo  Aguascalientes      01      003   931.300088
01004                  Cosio  Aguascalientes      01      004   128.907513
01005            Jesus Maria  Aguascalientes      01      005   499.207990
...                      ...             ...     ...      ...          ...
32053  Villa Gonzalez Ortega       Zacatecas      32      053   417.529939
32054          Villa Hidalgo       Zacatecas      32      054   355.528477
32055             Villanueva       Zacatecas      32      055  2158.696446
32056              Zacatecas       Zacatecas      32      056   444.547742
32057               Trancoso       Zacatecas      32      057   215.239163

                                                geometry  Cve. Municipio
CLAVE
01001  POLYGON ((1416489.577 2467700.472, 1417908.226...            1001
01002  POLYGON ((1417043.958 2491681.240, 1417408.488...            1002
01003  POLYGON ((1347882.273 2454901.097, 1348002.307...            1003
01004  POLYGON ((1397788.297 2509816.078, 1398009.089...            1004
01005  POLYGON ((1388272.165 2462097.533, 1389832.232...            1005
...                                                  ...             ...
32053  POLYGON ((1432967.088 2533295.874, 1432739.332...           32053
32054  POLYGON ((1464010.774 2518715.060, 1464186.335...           32054
32055  POLYGON ((1345756.044 2531084.706, 1346503.579...           32055
32056  POLYGON ((1339206.596 2548649.944, 1340025.280...           32056
32057  POLYGON ((1400816.550 2541592.398, 1400764.458...           32057

[2480 rows x 7 columns]>

In [94]:
crime2023.info

<bound method DataFrame.info of          Año Clave_Ent         Entidad  Cve. Municipio              Municipio  \
0       2023        01  Aguascalientes            1001         Aguascalientes
1       2023        01  Aguascalientes            1001         Aguascalientes
2       2023        01  Aguascalientes            1001         Aguascalientes
3       2023        01  Aguascalientes            1001         Aguascalientes
4       2023        01  Aguascalientes            1001         Aguascalientes
...      ...       ...             ...             ...                    ...
243329  2023        32       Zacatecas           32058  Santa María de la Paz
243330  2023        32       Zacatecas           32058  Santa María de la Paz
243331  2023        32       Zacatecas           32058  Santa María de la Paz
243332  2023        32       Zacatecas           32058  Santa María de la Paz
243333  2023        32       Zacatecas           32058  Santa María de la Paz

                                   Bien jurídico afectado  \
0                        La vida y la Integridad corporal
1                        La vida y la Integridad corporal
2                        La vida y la Integridad corporal
3                        La vida y la Integridad corporal
4                        La vida y la Integridad corporal
...                                                   ...
243329  Otros bienes jurídicos afectados (del fuero co...
243330  Otros bienes jurídicos afectados (del fuero co...
243331  Otros bienes jurídicos afectados (del fuero co...
243332  Otros bienes jurídicos afectados (del fuero co...
243333  Otros bienes jurídicos afectados (del fuero co...

                                   Tipo de delito  \
0                                       Homicidio
1                                       Homicidio
2                                       Homicidio
3                                       Homicidio
4                                       Homicidio
...                                           ...
243329                              Falsificación
243330                   Contra el medio ambiente
243331  Delitos cometidos por servidores públicos
243332                                Electorales
243333              Otros delitos del Fuero Común

                                Subtipo de delito  \
0                                Homicidio doloso
1                                Homicidio doloso
2                                Homicidio doloso
3                                Homicidio doloso
4                               Homicidio culposo
...                                           ...
243329                              Falsificación
243330                   Contra el medio ambiente
243331  Delitos cometidos por servidores públicos
243332                                Electorales
243333              Otros delitos del Fuero Común

                                        Modalidad  Enero  ...  Marzo  Abril  \
0                               Con arma de fuego      1  ...      2      1
1                                 Con arma blanca      2  ...      0      1
2                               Con otro elemento      1  ...      1      0
3                                 No especificado      0  ...      0      0
4                               Con arma de fuego      0  ...      0      0
...                                           ...    ...  ...    ...    ...
243329                              Falsificación      0  ...      0      0
243330                   Contra el medio ambiente      0  ...      0      0
243331  Delitos cometidos por servidores públicos      0  ...      0      0
243332                                Electorales      0  ...      0      0
243333              Otros delitos del Fuero Común      0  ...      1      0

        Mayo  Junio  Julio  Agosto  Septiembre  Octubre  Noviembre  Diciembre
0          1      1      1       4           1        1          0          2
1          0      2      0       3           1        0          3          0
2          0      3      0       0           1        1          2          1
3          0      0      0       0           0        0          0          0
4          0      0      0       0           0        0          0          0
...      ...    ...    ...     ...         ...      ...        ...        ...
243329     0      0      0       0           0        0          0          0
243330     0      0      0       0           0        0          0          0
243331     0      0      0       0           0        0          0          0
243332     0      0      0       0           0        0          0          0
243333     0      0      0       1           0        0          0          0

[243334 rows x 21 columns]>

In [70]:
# Convertir 'Cve. Municipio' a entero
#mx_mun['Cve. Municipio'] = mx_mun['Cve. Municipio'].astype(int)

# Ordenar el DataFrame en forma ascendente por 'Cve. Municipio' como entero
mx_mun = mx_mun.sort_values(by='Cve. Municipio', ascending=True)

In [77]:
mx_mun

,NOM_MUN,NOMEDO,CVE_EDO,CVE_MUNI,Area,geometry,Cve. Municipio
CLAVE,,,,,,,
01001,Aguascalientes,Aguascalientes,01,001,1168.762384,"POLYGON ((1416489.577 2467700.472, 1417908.226...",1001
01002,Asientos,Aguascalientes,01,002,547.762077,"POLYGON ((1417043.958 2491681.240, 1417408.488...",1002
01003,Calvillo,Aguascalientes,01,003,931.300088,"POLYGON ((1347882.273 2454901.097, 1348002.307...",1003
01004,Cosio,Aguascalientes,01,004,128.907513,"POLYGON ((1397788.297 2509816.078, 1398009.089...",1004
01005,Jesus Maria,Aguascalientes,01,005,499.207990,"POLYGON ((1388272.165 2462097.533, 1389832.232...",1005
...,...,...,...,...,...,...,...
32053,Villa Gonzalez Ortega,Zacatecas,32,053,417.529939,"POLYGON ((1432967.088 2533295.874, 1432739.332...",32053
32054,Villa Hidalgo,Zacatecas,32,054,355.528477,"POLYGON ((1464010.774 2518715.060, 1464186.335...",32054
32055,Villanueva,Zacatecas,32,055,2158.696446,"POLYGON ((1345756.044 2531084.706, 1346503.579...",32055
32056,Zacatecas,Zacatecas,32,056,444.547742,"POLYGON ((1339206.596 2548649.944, 1340025.280...",32056
32057,Trancoso,Zacatecas,32,057,215.239163,"POLYGON ((1400816.550 2541592.398, 1400764.458...",32057

In [78]:
import pandas as pd

# Assuming 'crime2023' is your DataFrame
# Display unique values in the 'Tipo de delito' column
unique_types = crime2023['Tipo de delito'].unique()
print("Unique values in 'Tipo de delito':")
print(unique_types)

# Display unique values in the 'Bien jurídico afectado' column
unique_subtypes = crime2023['Bien jurídico afectado'].unique()
print("\nUnique values in 'Bien jurídico afectado':")
print(unique_subtypes)

Unique values in 'Tipo de delito':
['Homicidio' 'Lesiones' 'Feminicidio' 'Aborto'
 'Otros delitos que atentan contra la vida y la integridad corporal'
 'Secuestro' 'Tráfico de menores' 'Rapto'
 'Otros delitos que atentan contra la libertad personal' 'Abuso sexual'
 'Acoso sexual' 'Hostigamiento sexual' 'Violación simple'
 'Violación equiparada' 'Incesto'
 'Otros delitos que atentan contra la libertad y la seguridad sexual'
 'Robo' 'Fraude' 'Abuso de confianza' 'Extorsión' 'Daño a la propiedad'
 'Despojo' 'Otros delitos contra el patrimonio' 'Violencia familiar'
 'Violencia de género en todas sus modalidades distinta a la violencia familiar'
 'Incumplimiento de obligaciones de asistencia familiar'
 'Otros delitos contra la familia' 'Corrupción de menores'
 'Trata de personas' 'Otros delitos contra la sociedad' 'Narcomenudeo'
 'Amenazas' 'Allanamiento de morada' 'Evasión de presos' 'Falsedad'
 'Falsificación' 'Contra el medio ambiente'
 'Delitos cometidos por servidores públicos' 'Electorales'
 'Otros delitos del Fuero Común']

Unique values in 'Bien jurídico afectado':
['La vida y la Integridad corporal' 'Libertad personal'
 'La libertad y la seguridad sexual' 'El patrimonio' 'La familia'
 'La sociedad' 'Otros bienes jurídicos afectados (del fuero común)']

In [79]:
# Filtramos primero por las categorías principales de 'Bien jurídico afectado'
categorias_deseadas = [
    "La libertad y la seguridad sexual",
    "La sociedad",
    "La vida y la Integridad corporal",
    "Libertad personal",
    "Otros bienes jurídicos afectados (del fuero común)"
]

filtered_crime2023 = crime2023[crime2023['Bien jurídico afectado'].isin(categorias_deseadas)]

# Ahora definimos las subcategorías específicas para filtrar en 'Tipo de delito'
# según corresponda a la categoría principal
subcategorias_filtro = {
    "La vida y la Integridad corporal": ["Feminicidio"],
    "Libertad personal": ["Tráfico de menores"],
    "Otros bienes jurídicos afectados (del fuero común)": ["Narcomenudeo", "Delitos cometidos por servidores públicos"]
}

# Aplicar filtro adicional basado en subcategorías específicas
def filtro_adicional(row):
    if row['Bien jurídico afectado'] in subcategorias_filtro:
        # Si hay subcategorías específicas, filtrar por ellas
        return row['Tipo de delito'] in subcategorias_filtro[row['Bien jurídico afectado']]
    else:
        # Si no hay subcategorías específicas, mantener la fila
        return True

# Aplicamos el filtro adicional
filtered_crime2023 = filtered_crime2023[filtered_crime2023.apply(filtro_adicional, axis=1)]

In [80]:
# Eliminar la columna "Modalidad"
filtered_crime2023 = filtered_crime2023.drop('Modalidad', axis=1)

# Lista de nombres de las columnas de los meses
meses = [
    "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
    "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
]

# Sumar las columnas de los meses para cada fila
filtered_crime2023['Total delitos'] = filtered_crime2023[meses].sum(axis=1)

# Eliminar las columnas individuales de los meses si ya no se necesitan
filtered_crime2023 = filtered_crime2023.drop(columns=meses)

In [81]:
filtered_crime2023

,Año,Clave_Ent,Entidad,Cve. Municipio,Municipio,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Total delitos
18,2023,01,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Feminicidio,Feminicidio,0
19,2023,01,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Feminicidio,Feminicidio,0
20,2023,01,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Feminicidio,Feminicidio,0
21,2023,01,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Feminicidio,Feminicidio,0
29,2023,01,Aguascalientes,1001,Aguascalientes,Libertad personal,Tráfico de menores,Tráfico de menores,0
...,...,...,...,...,...,...,...,...,...
243321,2023,32,Zacatecas,32058,Santa María de la Paz,La sociedad,Corrupción de menores,Corrupción de menores,0
243322,2023,32,Zacatecas,32058,Santa María de la Paz,La sociedad,Trata de personas,Trata de personas,0
243323,2023,32,Zacatecas,32058,Santa María de la Paz,La sociedad,Otros delitos contra la sociedad,Otros delitos contra la sociedad,0
243324,2023,32,Zacatecas,32058,Santa María de la Paz,Otros bienes jurídicos afectados (del fuero co...,Narcomenudeo,Narcomenudeo,0
243331,2023,32,Zacatecas,32058,Santa María de la Paz,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,0

In [82]:
def etiquetar(row):
    if row['Bien jurídico afectado'] == 'La vida y la Integridad corporal' and row['Tipo de delito'] == 'Feminicidio':
        return 'Violencia Mujeres, Familias y Niños'
    elif row['Bien jurídico afectado'] == 'Libertad personal' and row['Tipo de delito'] == 'Tráfico de menores':
        return 'Violencia Mujeres, Familias y Niños'
    elif row['Bien jurídico afectado'] == 'La libertad y la seguridad sexual':
        return 'Violencia Mujeres, Familias y Niños'
    elif row['Bien jurídico afectado'] == 'La sociedad':
        return 'Violencia Mujeres, Familias y Niños'
    
    elif row['Bien jurídico afectado'] == 'Otros bienes jurídicos afectados (del fuero común)' and row['Tipo de delito'] == 'Narcomenudeo':
        return 'Crimen Organizado'
    
    elif row['Bien jurídico afectado'] == 'Otros bienes jurídicos afectados (del fuero común)' and row['Tipo de delito'] == 'Delitos cometidos por servidores públicos':
        return 'Corrupción Institucional'
    else:
        return 'Otra categoría'  # o puedes elegir un valor predeterminado más específico

# Aplicar la función para crear la nueva columna de etiquetas
filtered_crime2023['Etiqueta'] = filtered_crime2023.apply(etiquetar, axis=1)

In [83]:
# Eliminar las columnas que no se necesitan
columns_to_drop = ['Bien jurídico afectado', 'Tipo de delito', 'Subtipo de delito']
df_reduced = filtered_crime2023.drop(columns=columns_to_drop)

# Agrupar por 'Cve. Municipio' y 'Etiqueta', y sumar los valores de 'Total delitos'
df_aggregated = df_reduced.groupby(['Entidad','Municipio','Cve. Municipio', 'Etiqueta']).agg({'Total delitos': 'sum'}).reset_index()

In [95]:
df_aggregated.info

<bound method DataFrame.info of              Entidad       Municipio  Cve. Municipio  \
0     Aguascalientes  Aguascalientes            1001
1     Aguascalientes  Aguascalientes            1001
2     Aguascalientes  Aguascalientes            1001
3     Aguascalientes        Asientos            1002
4     Aguascalientes        Asientos            1002
...              ...             ...             ...
7444       Zacatecas      Villanueva           32055
7445       Zacatecas      Villanueva           32055
7446       Zacatecas       Zacatecas           32056
7447       Zacatecas       Zacatecas           32056
7448       Zacatecas       Zacatecas           32056

                                 Etiqueta  Total delitos
0                Corrupción Institucional            474
1                       Crimen Organizado           1462
2     Violencia Mujeres, Familias y Niños           1011
3                Corrupción Institucional              4
4                       Crimen Organizado            108
...                                   ...            ...
7444                    Crimen Organizado              9
7445  Violencia Mujeres, Familias y Niños             15
7446             Corrupción Institucional             90
7447                    Crimen Organizado             71
7448  Violencia Mujeres, Familias y Niños            264

[7449 rows x 5 columns]>

In [85]:
# Seleccionar las columnas necesarias de 'mx_mun'
mx_mun_reduced = mx_mun[['NOMEDO','Cve. Municipio', 'NOM_MUN', 'Area', 'geometry']]

# Convertir 'Cve. Municipio' en ambos DataFrames a tipo int para asegurar una comparación correcta
mx_mun_reduced['Cve. Municipio'] = mx_mun_reduced['Cve. Municipio'].astype(int)
df_aggregated['Cve. Municipio'] = df_aggregated['Cve. Municipio'].astype(int)

# Realizar el merge
df_final = pd.merge(df_aggregated, mx_mun_reduced, on='Cve. Municipio', how='left')

/Users/pablouriarte/opt/anaconda3/lib/python3.9/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [86]:
# Resetear el índice del DataFrame para asegurar que no hayan duplicados
df_final = df_final.reset_index(drop=True)

In [91]:
df_final.info

<bound method DataFrame.info of              Entidad       Municipio  Cve. Municipio  \
0     Aguascalientes  Aguascalientes            1001
1     Aguascalientes  Aguascalientes            1001
2     Aguascalientes  Aguascalientes            1001
3     Aguascalientes        Asientos            1002
4     Aguascalientes        Asientos            1002
...              ...             ...             ...
7561       Zacatecas      Villanueva           32055
7562       Zacatecas      Villanueva           32055
7563       Zacatecas       Zacatecas           32056
7564       Zacatecas       Zacatecas           32056
7565       Zacatecas       Zacatecas           32056

                                 Etiqueta  Total delitos          NOMEDO  \
0                Corrupción Institucional            474  Aguascalientes
1                       Crimen Organizado           1462  Aguascalientes
2     Violencia Mujeres, Familias y Niños           1011  Aguascalientes
3                Corrupción Institucional              4  Aguascalientes
4                       Crimen Organizado            108  Aguascalientes
...                                   ...            ...             ...
7561                    Crimen Organizado              9       Zacatecas
7562  Violencia Mujeres, Familias y Niños             15       Zacatecas
7563             Corrupción Institucional             90       Zacatecas
7564                    Crimen Organizado             71       Zacatecas
7565  Violencia Mujeres, Familias y Niños            264       Zacatecas

             NOM_MUN         Area  \
0     Aguascalientes  1168.762384
1     Aguascalientes  1168.762384
2     Aguascalientes  1168.762384
3           Asientos   547.762077
4           Asientos   547.762077
...              ...          ...
7561      Villanueva  2158.696446
7562      Villanueva  2158.696446
7563       Zacatecas   444.547742
7564       Zacatecas   444.547742
7565       Zacatecas   444.547742

                                               geometry
0     POLYGON ((1416489.577 2467700.472, 1417908.226...
1     POLYGON ((1416489.577 2467700.472, 1417908.226...
2     POLYGON ((1416489.577 2467700.472, 1417908.226...
3     POLYGON ((1417043.958 2491681.240, 1417408.488...
4     POLYGON ((1417043.958 2491681.240, 1417408.488...
...                                                 ...
7561  POLYGON ((1345756.044 2531084.706, 1346503.579...
7562  POLYGON ((1345756.044 2531084.706, 1346503.579...
7563  POLYGON ((1339206.596 2548649.944, 1340025.280...
7564  POLYGON ((1339206.596 2548649.944, 1340025.280...
7565  POLYGON ((1339206.596 2548649.944, 1340025.280...

[7566 rows x 9 columns]>

In [88]:
# Intentar de nuevo filtrar para obtener solo las filas donde 'NOM_MUN' es NaN
nan_rows = df_final[df_final['NOM_MUN'].isna()]

In [89]:
nan_rows

,Entidad,Municipio,Cve. Municipio,Etiqueta,Total delitos,NOMEDO,NOM_MUN,Area,geometry
42,Baja California,San Felipe,2007,Corrupción Institucional,1,NaN,NaN,NaN,None
43,Baja California,San Felipe,2007,Crimen Organizado,22,NaN,NaN,NaN,None
44,Baja California,San Felipe,2007,"Violencia Mujeres, Familias y Niños",35,NaN,NaN,NaN,None
45,Baja California,San Quintín,2006,Corrupción Institucional,20,NaN,NaN,NaN,None
46,Baja California,San Quintín,2006,Crimen Organizado,58,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...
6871,Veracruz de Ignacio de la Llave,Santiago Sochiapan,30212,Crimen Organizado,0,NaN,NaN,NaN,None
6872,Veracruz de Ignacio de la Llave,Santiago Sochiapan,30212,"Violencia Mujeres, Familias y Niños",8,NaN,NaN,NaN,None
7512,Zacatecas,Santa María de la Paz,32058,Corrupción Institucional,0,NaN,NaN,NaN,None
7513,Zacatecas,Santa María de la Paz,32058,Crimen Organizado,0,NaN,NaN,NaN,None
7514,Zacatecas,Santa María de la Paz,32058,"Violencia Mujeres, Familias y Niños",2,NaN,NaN,NaN,None

In [104]:
# Eliminar todas las filas que tienen al menos un NaN en cualquier columna
df_final_clean = df_final.dropna()

In [106]:
print(df_final_clean['geometry'].head())

0    POLYGON ((1416489.577 2467700.472, 1417908.226...
1    POLYGON ((1416489.577 2467700.472, 1417908.226...
2    POLYGON ((1416489.577 2467700.472, 1417908.226...
3    POLYGON ((1417043.958 2491681.240, 1417408.488...
4    POLYGON ((1417043.958 2491681.240, 1417408.488...
Name: geometry, dtype: geometry

In [102]:
# Definir la ruta donde deseas guardar el shapefile
shapefile_path = "/Users/pablouriarte/Mapa_Migracion_Irregular_Mexico_Fresh/1. Mapas/1. Mapas/Metodo_1/areas/df_final_shape"

# Guardar el GeoDataFrame como shapefile
gdf.to_file(f"{shapefile_path}.shp")

print("Shapefile guardado con éxito en:", shapefile_path + ".shp")
push"

/var/folders/68/6zkv8z4j4rl6ds90br2rb7ph0000gn/T/ipykernel_7632/3149254785.py:5: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  gdf.to_file(f"{shapefile_path}.shp")

Shapefile guardado con éxito en: /Users/pablouriarte/Mapa_Migracion_Irregular_Mexico_Fresh/1. Mapas/1. Mapas/Metodo_1/areas/df_final_shape.shp

In [103]:
# Guardar el DataFrame final en un archivo CSV
#path = "/Users/pablouriarte/Mapa_Migracion_Irregular_Mexico_Fresh/1. Mapas/1. Mapas/Metodo_1/areas/riskzone.csv"
#df_final_clean.to_csv(path, index=False)

In [ ]:
import gzip
import shutil

# Ruta del archivo original
#path_original = "/Users/pablouriarte/Documents/1. Expediente Tec de Monterrey/1.Tesis/Mapa_Migracion_Irregular_Mexico/1. Mapas/1. Mapas/Metodo_1/areas/riskzone.csv"
# Ruta del archivo comprimido
path_comprimido = "/Users/pablouriarte/Documents/1. Expediente Tec de Monterrey/1.Tesis/Mapa_Migracion_Irregular_Mexico/1. Mapas/1. Mapas/Metodo_1/areas/riskzone.csv.gz"

# Abrir el archivo original y el archivo comprimido
with open(path_original, 'rb') as f_in, gzip.open(path_comprimido, 'wb') as f_out:
    # Copiar el contenido del archivo original al archivo comprimido usando gzip
    shutil.copyfileobj(f_in, f_out)

print("Archivo comprimido con éxito.")